name: Deploy to Vercel

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    # Only run if PR is merged to master
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project
        run: |
          cd backend
          npm install
          npm run build

      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          USE_PYTHON_SERVER: ${{ secrets.USE_PYTHON_SERVER }}
          USE_CREDLY_BADGES: ${{ secrets.USE_CREDLY_BADGES }}
          USE_VALIDATE_CERT: ${{ secrets.USE_VALIDATE_CERT }}
          USE_ADD_MENTES: ${{ secrets.USE_ADD_MENTES }}
          SERVER_SEC_KEY: ${{ secrets.SERVER_SEC_KEY }}
          MONGODB_CONN_URI: ${{ secrets.MONGODB_CONN_URI }}